### ISSUE TITLE
Weekly Report typos

### ISSUE THREAD

**Issue by Victor-Leroy** [algosup/2023-2024-project-2-x86-retrogaming-team-1#11]
add Victor LEROY to the reviewers 👍
line 57 ~github~ -> GitHub
use ✅⌛️❌ instead of done or work in progress, in order to have a better visual
line 81 start *writing* it
line 87 dot missing at the end of the line
line 109 Abderrazaq Namir ? 
line 117 same issue as line 81
line 220 what is planned for next week
line 234 technical specifications *is*
line 258 weird phrasing
line 270 *software* engineers
line 274 Abderrazaq Namir again ??
line 323 icant (Abderrazaq Namir once again)
line 343 *G*oogle

**Comment by AlexisLasselin** [comment]
@Victor-Leroy Check if everything is fine, the file is pushed

**Comment by Victor-Leroy** [comment]
to do : purpose, add a small description about what every symbol represents

**Comment by Victor-Leroy** [comment]
line 226 ~but~ -> and

**Comment by AlexisLasselin** [comment]
You are now able to check again.😁
