### ISSUE TITLE
Letter appearing when moving Pac-Man 

### ISSUE THREAD

**Issue by Victor-Leroy** [algosup/2023-2024-project-2-x86-retrogaming-team-1#12]
In order to reproduce this bug, you simply have to move Pac-Man in any direction.

![LetterBug](https://github.com/algosup/2023-2024-project-2-x86-retrogaming-team-1/assets/97166029/c7e0794c-ac6a-439d-b464-13be1d6407fe)

**Comment by JasonGROSSO** [comment]
fixed but new bugs appeared due to fix ( will fix those also)
